### ISSUE TITLE
license

### ISSUE THREAD

**Issue by egull** [ALPSCore/GFTools#1]
@aeantipov @galexv Any objections to making the license GPLv2 from the beginning? This will make merging later on easier...

**Comment by aeantipov** [comment]
Sure, no problems

**Comment by galexv** [comment]
I do not have strong opinion on this. ALPSCore license is GPLv2, but the original Andrey's code, from which i am going to borrow heavily, is MIT-licensed. So, the question is to Andrey...

**Comment by aeantipov** [comment]
It better be the same as alpscore, so GPLv2 in fact should be used

**Comment by egull** [comment]
OK, changed to the ALPSCore license
